import "/styles/globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/sonner";

export const metadata = {
  title: "ecomus",
  description: "Generated by create next app",
  icons: {
    icon: "//ecomus-2-2.myshopify.com/cdn/shop/files/Favicon.png?crop=center&height=32&v=1744272797&width=32",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-background font-sans antialiased">
        <Header />
        {children}
        <Footer />
        <Toaster />
      </body>
    </html>
  );
}
