import "/styles/globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/sonner";

export const metadata = {
  title: "ecomus",
  description: "Generated by create next app",
  icons: {
    icon: {
      url: "https://ecomus-2-2.myshopify.com/cdn/shop/files/Favicon.png?crop=center&height=32&v=1744272797&width=32",
      type: "image/png",
    },
    apple: {
      url: "https://ecomus-2-2.myshopify.com/cdn/shop/files/Favicon.png?crop=center&height=180&v=1744272797&width=180",
      type: "image/png",
      sizes: "180x180",
      rel: "apple-touch-icon",
    },
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
        <Toaster />
      </body>
    </html>
  );
}
